# Usar a imagem oficial do Python
FROM python:3.9

# Definir o diretório de trabalho no container
WORKDIR /code

# Copiar os arquivos de requisitos para o container
COPY requirements.txt /code/

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação para o container
COPY . /code/

# Comando para executar o Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]