# Generated by Django 5.1 on 2024-11-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado'), ('CONFIRMADO', 'Confirmado')], default='PENDENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='segunda', max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disponivel', models.CharField(default='T', max_length=1)),
            ],
            options={
                'db_table': 'HorarioEspecialista',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('dt_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_profissionais/')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('fuso_horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('dt_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('id_especialidade', models.IntegerField()),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('tempo_atuacao', models.PositiveIntegerField(null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_profissionais/')),
                ('fuso_horario', models.CharField(default='UTC', max_length=50)),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade_atendimento', models.CharField(choices=[('online ', 'Online'), ('presencial', 'Presencial'), ('ambos', 'Ambos')], default='online', max_length=100)),
            ],
            options={
                'db_table': 'Profissional',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('prescricoes', models.TextField(blank=True, null=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profissional.agendamento')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.horarioespecialista'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.profissional'),
        ),
        migrations.AddField(
            model_name='horarioespecialista',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.profissional'),
        ),
        migrations.CreateModel(
            name='EnderecoEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('id_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='Profissional.profissional')),
            ],
            options={
                'db_table': 'endereco_especialista',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrela', models.IntegerField()),
                ('comentario', models.TextField()),
                ('paciente', models.IntegerField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Profissional.profissional')),
            ],
            options={
                'db_table': 'avaliacoes',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.profissional'),
        ),
    ]
