# Generated by Django 5.1 on 2024-09-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0002_profissional_delete_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profissional',
            table='Profissional',
        ),
    ]
