# Generated by Django 5.1 on 2024-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0003_consulta_valor_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_ultima_consulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
