# Generated by Django 5.1 on 2024-09-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0004_profissional_chave_pix_profissional_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='id_horario',
        ),
        migrations.CreateModel(
            name='HorarioEspecialista',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horarios', models.CharField(max_length=255)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profissional.profissional')),
            ],
            options={
                'db_table': 'HorarioEspecialista',
            },
        ),
    ]
