# Generated by Django 5.1 on 2024-11-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0004_alter_paciente_dt_ultima_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='tipo_secao',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial'), ('INDISPONIVEL', 'Indiponivel')], default='ONLINE'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_paciente',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='Profissional.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profissional.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='telefone_paciente',
            field=models.CharField(blank=True, null=True),
        ),
    ]
