# Generated by Django 5.1 on 2024-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0005_agendamento_tipo_secao_consulta_data_consulta_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_secao',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial'), ('INDISPONIVEL', 'Indiponivel')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_realizacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
