# Generated by Django 5.1 on 2024-09-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0005_remove_profissional_id_horario_horarioespecialista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioespecialista',
            old_name='horarios',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='horarioespecialista',
            old_name='especialista',
            new_name='id_profissional',
        ),
    ]
