# Generated by Django 5.1 on 2024-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0006_alter_agendamento_tipo_secao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='link_video_chamada',
            field=models.CharField(blank=True, null=True),
        ),
    ]
