# Generated by Django 5.1 on 2024-09-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0006_rename_horarios_horarioespecialista_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrela', models.IntegerField()),
                ('comentario', models.TextField()),
                ('paciente', models.IntegerField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Profissional.profissional')),
            ],
            options={
                'db_table': 'avaliacoes',
            },
        ),
        migrations.CreateModel(
            name='EnderecoEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('id_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='Profissional.profissional')),
            ],
            options={
                'db_table': 'endereco_especialista',
            },
        ),
    ]
