# Generated by Django 5.1 on 2024-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0007_consulta_link_video_chamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nome_paciente',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
