# Generated by Django 5.1 on 2024-12-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0008_alter_consulta_nome_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='situacao',
            field=models.CharField(blank=True, choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='Aberta'),
        ),
    ]
