# Generated by Django 5.1 on 2024-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0009_consulta_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='situacao',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='Aberta'),
        ),
    ]
