# Generated by Django 5.1 on 2024-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0010_alter_consulta_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='situacao',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta'),
        ),
    ]
