# Generated by Django 5.1 on 2024-12-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profissional', '0011_alter_consulta_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fuso_horario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
